# Site settings
title: PHYSICAL THERAPIST turned COMPUTER PROGRAMMER
header-img: img/home-bg.png
email: yatescjnd@gmail.com
copyright_name: yatescj
description: > # this means to ignore newlines until "baseurl:"
  From talking to patients to talking to the little black box 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  yatescj
learn_profile: yatescj
email_username: yatescjnd@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
